### ISSUE TITLE
[FEATURE] 메모 전체조회 기능, ai 응답 리팩터링을 진행한다. 

### ISSUE THREAD

**Issue by BaeJinho4028** [swm-null/null_backend#5]
# ✅ 메모 전체조회 기능, ai 응답 리팩터링을 진행한다. 

## ✏ TODO
- [ ] 메모 전체조회 기능
- [ ] ai 응답 리팩터링
- [ ] 메모 응답 리팩터링

## 📖 참고 할만한 자료
![image](https://github.com/swm-null/null_backend/assets/72592302/54f3dac7-fee1-4a6e-81af-6e9753da7414)
